/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const decrypt: (a: number, b: number, c: number, d: number, e: number, f: number, g: any) => [number, number, number];
export const encrypt: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const extract_public_key: (a: number, b: number) => [number, number, number, number];
export const generate_key: (a: any) => [number, number, number];
export const inspect_key: (a: number, b: number) => [number, number, number];
export const sign_cleartext: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const sign_detached: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const start: () => void;
export const vault_create: (a: number, b: number) => [number, number, number];
export const vault_decrypt: (a: any, b: number, c: number, d: any) => [number, number, number, number];
export const vault_encrypt: (a: any, b: number, c: number) => [number, number, number];
export const vault_verify_password: (a: any, b: number, c: number) => [number, number, number];
export const verify_cleartext: (a: number, b: number, c: number, d: number) => [number, number, number];
export const verify_detached: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const version: () => [number, number];
export const LIBBZ2_RS_SYS_v0.1.x_BZ2_bzDecompress: (a: number) => number;
export const LIBBZ2_RS_SYS_v0.1.x_BZ2_bzDecompressInit: (a: number, b: number, c: number) => number;
export const LIBBZ2_RS_SYS_v0.1.x_BZ2_bzCompressInit: (a: number, b: number, c: number, d: number) => number;
export const LIBBZ2_RS_SYS_v0.1.x_BZ2_bzCompress: (a: number, b: number) => number;
export const LIBBZ2_RS_SYS_v0.1.x_BZ2_bzCompressEnd: (a: number) => number;
export const LIBBZ2_RS_SYS_v0.1.x_BZ2_bzDecompressEnd: (a: number) => number;
export const LIBBZ2_RS_SYS_v0.1.x_BZ2_bzBuffToBuffCompress: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const LIBBZ2_RS_SYS_v0.1.x_BZ2_bzBuffToBuffDecompress: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
